name: chatgpt
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #State Management
  flutter_bloc: ^8.1.3
  #for Splash screen
  flutter_native_splash: ^2.3.6
  # an svg rendering
  flutter_svg: ^2.0.9
  #adapting screen and font size
  flutter_screenutil: ^5.9.0
  #local database
  shared_preferences: ^2.1.1
  #page indicator
  smooth_page_indicator: ^1.1.0
  #messages
  flutter_chat_bubble: ^2.0.2
  #A composable, multi-platform, Future-based API for HTTP requests.
  http: ^1.1.2
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2





flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon.png"



dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
   - assets/image/
   - assets/svg/


  fonts:
     - family: Raleway
       fonts:
         - asset: assets/font/Raleway.ttf
         - asset: assets/font/Raleway-Bold.ttf
           weight: 700
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

